### ISSUE TITLE
Add support for iptables, giving everyone cheap security group type behavior

### ISSUE THREAD

**Issue by phildougherty** [containership/containership#28]
Opening ports in the firewall automatically as they are allocated by an application would be ideal.

More advanced possibilities: 
* Only open the ports to other followers that have an application that is linking to the one being started
* Allow users to define custom rules for addresses or network to allow/deny access to/from.

**Comment by phildougherty** [comment]
I picture this happening on the host system, so containership would need to be running as root or have permissions to change iptables rules.

**Comment by normanjoyner** [comment]
will be handled by containership/containership.plugin.firewall
