### ISSUE TITLE
Add support for plugin configuration/parameters

### ISSUE THREAD

**Issue by phildougherty** [containership/containership#30]
We need to be able to set some configuration for specific plugins (like the cloud plugin for example). Other plugins we plan to make require this to be possible as well.

**Comment by normanjoyner** [comment]
Implemented in https://github.com/containership/containership.cli/commit/5005cd8cb8f0d5ea934f9dfa806a3a0c57a769e0 and available starting in containership.cli version 0.2.3. 

example usage:
`containership plugin configure cloud --api-key abc123 --organization myorg`
