### ISSUE TITLE
write to stderr when running with insufficient privileges

### ISSUE THREAD

**Issue by normanjoyner** [containership/containership#46]
containership agent fails silently when logging to file with insufficient privileges. Write an error to stderr to notify the user.

**Comment by dimitrovskif** [comment]
I tried to solve this in the containership.cli repo, but I can't find the `agent` handler anywhere...

**Comment by normanjoyner** [comment]
the agent command is defined here:
https://github.com/containership/containership/blob/master/application.js#L28 

and all the CLI commands are merged into the commands object here: https://github.com/containership/containership/blob/master/application.js#L55

**Comment by dimitrovskif** [comment]
Well it seems that the process should stop if running with insufficient privileges. However, I tried running it without sudo on a non-root user and that does not happen with the latest npm build.

Any idea?

**Comment by normanjoyner** [comment]
the process should stop as seen below, when running as a non-root user (without sudo):

```
→ npm install containership -g
containership@0.2.3 /usr/local/lib/node_modules/containership
→ ps aux | grep node
normanjoyner     5010   0.0  0.0  2432772    568 s005  R+    5:47PM   0:00.00 grep node
→ containership agent --mode leader
→ ps aux | grep node
normanjoyner     5016   0.0  0.0  2432772    528 s005  R+    5:47PM   0:00.00 grep node
```

as opposed to the following when running as sudo:

```
→ ps aux | grep node
normanjoyner     5021   0.0  0.0  2434820    576 s005  R+    5:49PM   0:00.00 grep node
→ sudo containership agent --mode leader
→ ps aux | grep node
root             5025  16.7  1.0  3082192  82052   ??  Ss    5:49PM   0:01.07 /usr/local/bin/node /usr/local/bin/containership agent --mode leader
normanjoyner     5034   0.0  0.0  2432772    556 s005  R+    5:49PM   0:00.00 grep node
```

can you paste what you are experiencing so I can troubleshoot?

**Comment by normanjoyner** [comment]
@dimitrovskif I am proposing the following output to notify users they are not running with enough privileges:

```
→ containership agent --mode leader
Error writing PID! Are you running containership as root?
```
