### ISSUE TITLE
Available cluster memory tracking inaccurate 

### ISSUE THREAD

**Issue by phildougherty** [containership/containership#6]
I have 4 followers. Total available memory is 1.8GB

I created an application (redis) with 0.01 cpus and 8MB RAM for testing. 

I scaled it up to 70 containers, it stopped scaling at 29/70.

○ → for i in `seq 1 4`; do ssh root@follower$i docker ps -q; done|wc -l
      33

33 are actually running (including my 4 service-discovery containers).

The cluster thinks only 48MB is available.

**Comment by normanjoyner** [comment]
Your cluster's available memory is 1848MB.

You have 4 128MB containership-haproxy containers and 29 8MB redis containers, for a total of 744MB.

ContainerShip allocates an additional 32MB per container, which will add an additional 1056MB.

The 48MB free is derived from `1848 - (744 + 1056)`

**Comment by normanjoyner** [comment]
@phildougherty I believe this still needs to be added to the new documentation

**Comment by normanjoyner** [comment]
Not sure if documentation has been updated with this info
