### ISSUE TITLE
List version of containership installed on hosts detail view in Navigator

### ISSUE THREAD

**Issue by phildougherty** [containership/containership#8]
It would be helpful to be able to see what version of containership is currently installed on each host in the cluster. That way you could be have more confidence that your job is done after an upgrade.

**Comment by phildougherty** [comment]
Should probably also list the version of docker installed as well while we're at it.

**Comment by normanjoyner** [comment]
New version of containership.scheduler (myriad-kv integration) will expose engine information beneath the host metadata.engine tag. This information will be visible in Navigator on the host detail page, and generally available via the API.

**Comment by normanjoyner** [comment]
I will expose the containership version in the same manner as explained above.
